In [1]:
import numpy as np
import pandas as pd

In [2]:
class NQueensSolver:
    def __init__(self):
        pass
        
    def set_queen(self, i, j, chessboard):
        new_chessboard = chessboard.copy()
        new_chessboard[i, j] = 1
        return new_chessboard
        
    def remove_queen(self, i, j, chessboard):
        new_chessboard = chessboard.copy()
        new_chessboard[i, j] = 0
        return new_chessboard
        
    def check_queen(self, i, j, n, chessboard):
        
        def in_boundary(row, col):
            return 0 <= row < n and 0 <= col < n
        
        # check row
        for col in range(n):
            if col != j and chessboard[i, col] == 1:
                return False

        # check column
        for row in range(n):
            if row != i and chessboard[row, j] == 1:
                return False

        # check diagonals
        diff = 0
        while in_boundary(i - diff, j - diff):
            if chessboard[i - diff, j - diff] == 1:
                return False
            diff += 1
            
        diff = 0
        while in_boundary(i - diff, j + diff):
            if chessboard[i - diff, j + diff] == 1:
                return False
            diff += 1
            
        diff = 0
        while in_boundary(i + diff, j - diff):
            if chessboard[i + diff, j - diff] == 1:
                return False
            diff += 1
            
        diff = 0
        while in_boundary(i + diff, j + diff):
            if chessboard[i + diff, j + diff] == 1:
                return False
            diff += 1

        return True
        
    def solve(self, n): # Depth Tree Search with Stack
        solutions = []
        root_data = {
            'row':-1,
            'chessboard': np.zeros((n, n), dtype=int)
        }
        
        stack = [root_data]
        while len(stack) > 0:
            data = stack.pop()
            
            row = data['row']
            chessboard = data['chessboard']
            
            if row == n - 1:
                solutions.append(chessboard)
            else:
                row += 1
                
                for col in range(n):
                    if self.check_queen(row, col, n, chessboard):
                        stack.append({
                                        'row': row, 
                                        'chessboard': self.set_queen(row, col, chessboard)
                                    })
        
        return solutions

In [3]:
solver = NQueensSolver()
for soln in solver.solve(5):
    print(soln, '\n')

[[0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]] 

[[0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]] 

[[0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]] 

[[0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]] 

[[0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]] 

[[0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 1]] 

[[0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]] 

[[0 1 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]] 

[[1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]] 

[[1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]] 



In [4]:
solver = NQueensSolver()
total = 10

df = pd.DataFrame({
    'n': range(1, total + 1),
    '#solutions': list(map(lambda n: len(solver.solve(n)), range(1, total + 1)))
})
df[['n', '#solutions']]

n  #solutions
0   1           1
1   2           0
2   3           0
3   4           2
4   5          10
5   6           4
6   7          40
7   8          92
8   9         352
9  10         724